/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Hospital Management System
 * OpenAPI spec version: 1.0.0
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

/**
 * Schema for creating a diagnosis.
 */
export interface DiagnosisCreate {
  /**
   * @minLength 2
   * @maxLength 100
   */
  name: string;
}

/**
 * Schema for diagnosis responses.
 */
export interface DiagnosisResponse {
  /**
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  id: number;
}

export type DiagnosisUpdateName = string | null;

/**
 * Schema for updating a diagnosis.
 */
export interface DiagnosisUpdate {
  name?: DiagnosisUpdateName;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/**
 * Schema for login request.
 */
export interface LoginRequest {
  /** @minLength 3 */
  username: string;
  /** @minLength 6 */
  password: string;
}

export type PatientCreateFatherName = string | null;

export type PatientCreateWardId = number | null;

/**
 * Schema for creating a patient.
 */
export interface PatientCreate {
  /**
   * @minLength 2
   * @maxLength 50
   */
  first_name: string;
  /**
   * @minLength 2
   * @maxLength 50
   */
  last_name: string;
  father_name?: PatientCreateFatherName;
  diagnosis_id: number;
  ward_id?: PatientCreateWardId;
}

export type PatientResponseFatherName = string | null;

export type PatientResponseWardId = number | null;

/**
 * Schema for patient responses.
 */
export interface PatientResponse {
  /**
   * @minLength 2
   * @maxLength 50
   */
  first_name: string;
  /**
   * @minLength 2
   * @maxLength 50
   */
  last_name: string;
  father_name?: PatientResponseFatherName;
  diagnosis_id: number;
  ward_id?: PatientResponseWardId;
  id: number;
}

export type PatientUpdateFirstName = string | null;

export type PatientUpdateLastName = string | null;

export type PatientUpdateFatherName = string | null;

export type PatientUpdateDiagnosisId = number | null;

export type PatientUpdateWardId = number | null;

/**
 * Schema for updating a patient.
 */
export interface PatientUpdate {
  first_name?: PatientUpdateFirstName;
  last_name?: PatientUpdateLastName;
  father_name?: PatientUpdateFatherName;
  diagnosis_id?: PatientUpdateDiagnosisId;
  ward_id?: PatientUpdateWardId;
}

export type RegisterRequestFatherName = string | null;

/**
 * Schema for registration request.
 */
export interface RegisterRequest {
  /** @minLength 3 */
  email: string;
  /** @minLength 3 */
  username: string;
  /** @minLength 6 */
  password: string;
  /** @minLength 2 */
  first_name: string;
  /** @minLength 2 */
  last_name: string;
  father_name?: RegisterRequestFatherName;
}

/**
 * Schema for authentication token.
 */
export interface Token {
  access_token: string;
  token_type?: string;
}

export type UserCreateFatherName = string | null;

/**
 * Schema for creating a user.
 */
export interface UserCreate {
  email: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /**
   * @minLength 2
   * @maxLength 50
   */
  first_name: string;
  /**
   * @minLength 2
   * @maxLength 50
   */
  last_name: string;
  father_name?: UserCreateFatherName;
  role?: UserRole;
  is_active?: boolean;
  /** @minLength 6 */
  password: string;
}

export type UserResponseFatherName = string | null;

/**
 * Schema for user responses.
 */
export interface UserResponse {
  email: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /**
   * @minLength 2
   * @maxLength 50
   */
  first_name: string;
  /**
   * @minLength 2
   * @maxLength 50
   */
  last_name: string;
  father_name?: UserResponseFatherName;
  role?: UserRole;
  is_active?: boolean;
  id: number;
}

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  admin: "admin",
  doctor: "doctor",
  nurse: "nurse",
} as const;

export type UserUpdateEmail = string | null;

export type UserUpdateUsername = string | null;

export type UserUpdateFirstName = string | null;

export type UserUpdateLastName = string | null;

export type UserUpdateFatherName = string | null;

export type UserUpdateRole = UserRole | null;

export type UserUpdateIsActive = boolean | null;

export type UserUpdatePassword = string | null;

/**
 * Schema for updating a user.
 */
export interface UserUpdate {
  email?: UserUpdateEmail;
  username?: UserUpdateUsername;
  first_name?: UserUpdateFirstName;
  last_name?: UserUpdateLastName;
  father_name?: UserUpdateFatherName;
  role?: UserUpdateRole;
  is_active?: UserUpdateIsActive;
  password?: UserUpdatePassword;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type WardCreateDiagnosisId = number | null;

/**
 * Schema for creating a ward.
 */
export interface WardCreate {
  /**
   * @minLength 2
   * @maxLength 50
   */
  name: string;
  /**
   * @maximum 100
   */
  max_capacity: number;
  diagnosis_id?: WardCreateDiagnosisId;
}

export type WardResponseDiagnosisId = number | null;

/**
 * Schema for ward responses.
 */
export interface WardResponse {
  /**
   * @minLength 2
   * @maxLength 50
   */
  name: string;
  /**
   * @maximum 100
   */
  max_capacity: number;
  diagnosis_id?: WardResponseDiagnosisId;
  id: number;
  current_occupancy?: number;
}

export type WardUpdateName = string | null;

export type WardUpdateMaxCapacity = number | null;

export type WardUpdateDiagnosisId = number | null;

/**
 * Schema for updating a ward.
 */
export interface WardUpdate {
  name?: WardUpdateName;
  max_capacity?: WardUpdateMaxCapacity;
  diagnosis_id?: WardUpdateDiagnosisId;
}

export type GetUsersApiV1UsersGetParams = {
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  role?: string;
};

export type GetDiagnosesApiV1DiagnosesGetParams = {
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type GetWardsApiV1WardsGetParams = {
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  diagnosis_id?: number;
};

export type GetPatientsApiV1PatientsGetParams = {
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  diagnosis_id?: number;
  ward_id?: number;
};

export type SearchPatientsApiV1PatientsSearchGetParams = {
  /**
   * @minLength 2
   */
  query: string;
};

export const getHospitalManagementSystem = () => {
  /**
   * Root endpoint with API information.
   * @summary Root
   */
  const rootGet = <TData = AxiosResponse<unknown>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/`, options);
  };

  /**
   * Health check endpoint.
   * @summary Health Check
   */
  const healthCheckHealthGet = <TData = AxiosResponse<unknown>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/health`, options);
  };

  /**
   * Login user and get access token.
   * @summary Login
   */
  const loginApiV1AuthLoginPost = <TData = AxiosResponse<Token>>(
    loginRequest: LoginRequest,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(`/api/v1/auth/login`, loginRequest, options);
  };

  /**
   * Register a new user.
   * @summary Register
   */
  const registerApiV1AuthRegisterPost = <TData = AxiosResponse<unknown>>(
    registerRequest: RegisterRequest,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/auth/register`,
      registerRequest,
      options,
    );
  };

  /**
   * Get current user information.
   * @summary Get Current User Info
   */
  const getCurrentUserInfoApiV1AuthMeGet = <TData = AxiosResponse<unknown>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/auth/me`, options);
  };

  /**
   * Get all users (admin only).
   * @summary Get Users
   */
  const getUsersApiV1UsersGet = <TData = AxiosResponse<UserResponse[]>>(
    params?: GetUsersApiV1UsersGetParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/users/`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * Create a new user (admin only).
   * @summary Create User
   */
  const createUserApiV1UsersPost = <TData = AxiosResponse<UserResponse>>(
    userCreate: UserCreate,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(`/api/v1/users/`, userCreate, options);
  };

  /**
   * Get user by ID (admin only).
   * @summary Get User
   */
  const getUserApiV1UsersUserIdGet = <TData = AxiosResponse<UserResponse>>(
    userId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/users/${userId}`, options);
  };

  /**
   * Update user (admin only).
   * @summary Update User
   */
  const updateUserApiV1UsersUserIdPut = <TData = AxiosResponse<UserResponse>>(
    userId: number,
    userUpdate: UserUpdate,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.put(`/api/v1/users/${userId}`, userUpdate, options);
  };

  /**
   * Delete user (admin only).
   * @summary Delete User
   */
  const deleteUserApiV1UsersUserIdDelete = <TData = AxiosResponse<void>>(
    userId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.delete(`/api/v1/users/${userId}`, options);
  };

  /**
   * Get all diagnoses.
   * @summary Get Diagnoses
   */
  const getDiagnosesApiV1DiagnosesGet = <
    TData = AxiosResponse<DiagnosisResponse[]>,
  >(
    params?: GetDiagnosesApiV1DiagnosesGetParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/diagnoses/`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * Create a new diagnosis (admin only).
   * @summary Create Diagnosis
   */
  const createDiagnosisApiV1DiagnosesPost = <
    TData = AxiosResponse<DiagnosisResponse>,
  >(
    diagnosisCreate: DiagnosisCreate,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(`/api/v1/diagnoses/`, diagnosisCreate, options);
  };

  /**
   * Get diagnosis by ID.
   * @summary Get Diagnosis
   */
  const getDiagnosisApiV1DiagnosesDiagnosisIdGet = <
    TData = AxiosResponse<DiagnosisResponse>,
  >(
    diagnosisId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/diagnoses/${diagnosisId}`, options);
  };

  /**
   * Update diagnosis (admin only).
   * @summary Update Diagnosis
   */
  const updateDiagnosisApiV1DiagnosesDiagnosisIdPut = <
    TData = AxiosResponse<DiagnosisResponse>,
  >(
    diagnosisId: number,
    diagnosisUpdate: DiagnosisUpdate,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.put(
      `/api/v1/diagnoses/${diagnosisId}`,
      diagnosisUpdate,
      options,
    );
  };

  /**
   * Delete diagnosis (admin only).
   * @summary Delete Diagnosis
   */
  const deleteDiagnosisApiV1DiagnosesDiagnosisIdDelete = <
    TData = AxiosResponse<void>,
  >(
    diagnosisId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.delete(`/api/v1/diagnoses/${diagnosisId}`, options);
  };

  /**
   * Get all wards.
   * @summary Get Wards
   */
  const getWardsApiV1WardsGet = <TData = AxiosResponse<WardResponse[]>>(
    params?: GetWardsApiV1WardsGetParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/wards/`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * Create a new ward (admin only).
   * @summary Create Ward
   */
  const createWardApiV1WardsPost = <TData = AxiosResponse<WardResponse>>(
    wardCreate: WardCreate,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(`/api/v1/wards/`, wardCreate, options);
  };

  /**
   * Get wards with available beds.
   * @summary Get Available Wards
   */
  const getAvailableWardsApiV1WardsAvailableGet = <
    TData = AxiosResponse<WardResponse[]>,
  >(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/wards/available`, options);
  };

  /**
   * Get ward by ID.
   * @summary Get Ward
   */
  const getWardApiV1WardsWardIdGet = <TData = AxiosResponse<WardResponse>>(
    wardId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/wards/${wardId}`, options);
  };

  /**
   * Update ward (admin only).
   * @summary Update Ward
   */
  const updateWardApiV1WardsWardIdPut = <TData = AxiosResponse<WardResponse>>(
    wardId: number,
    wardUpdate: WardUpdate,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.put(`/api/v1/wards/${wardId}`, wardUpdate, options);
  };

  /**
   * Delete ward (admin only).
   * @summary Delete Ward
   */
  const deleteWardApiV1WardsWardIdDelete = <TData = AxiosResponse<void>>(
    wardId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.delete(`/api/v1/wards/${wardId}`, options);
  };

  /**
   * Get all patients.
   * @summary Get Patients
   */
  const getPatientsApiV1PatientsGet = <
    TData = AxiosResponse<PatientResponse[]>,
  >(
    params?: GetPatientsApiV1PatientsGetParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/patients/`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * Create a new patient (doctor only).
   * @summary Create Patient
   */
  const createPatientApiV1PatientsPost = <
    TData = AxiosResponse<PatientResponse>,
  >(
    patientCreate: PatientCreate,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(`/api/v1/patients/`, patientCreate, options);
  };

  /**
   * Search patients by name.
   * @summary Search Patients
   */
  const searchPatientsApiV1PatientsSearchGet = <
    TData = AxiosResponse<PatientResponse[]>,
  >(
    params: SearchPatientsApiV1PatientsSearchGetParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/patients/search`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * Get patients by diagnosis.
   * @summary Get Patients By Diagnosis
   */
  const getPatientsByDiagnosisApiV1PatientsDiagnosisDiagnosisIdGet = <
    TData = AxiosResponse<PatientResponse[]>,
  >(
    diagnosisId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(
      `/api/v1/patients/diagnosis/${diagnosisId}`,
      options,
    );
  };

  /**
   * Get patients in a ward.
   * @summary Get Patients By Ward
   */
  const getPatientsByWardApiV1PatientsWardWardIdGet = <
    TData = AxiosResponse<PatientResponse[]>,
  >(
    wardId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/patients/ward/${wardId}`, options);
  };

  /**
   * Get patient by ID.
   * @summary Get Patient
   */
  const getPatientApiV1PatientsPatientIdGet = <
    TData = AxiosResponse<PatientResponse>,
  >(
    patientId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/patients/${patientId}`, options);
  };

  /**
   * Update patient (doctor only).
   * @summary Update Patient
   */
  const updatePatientApiV1PatientsPatientIdPut = <
    TData = AxiosResponse<PatientResponse>,
  >(
    patientId: number,
    patientUpdate: PatientUpdate,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.put(
      `/api/v1/patients/${patientId}`,
      patientUpdate,
      options,
    );
  };

  /**
   * Delete patient (doctor only).
   * @summary Delete Patient
   */
  const deletePatientApiV1PatientsPatientIdDelete = <
    TData = AxiosResponse<void>,
  >(
    patientId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.delete(`/api/v1/patients/${patientId}`, options);
  };

  return {
    rootGet,
    healthCheckHealthGet,
    loginApiV1AuthLoginPost,
    registerApiV1AuthRegisterPost,
    getCurrentUserInfoApiV1AuthMeGet,
    getUsersApiV1UsersGet,
    createUserApiV1UsersPost,
    getUserApiV1UsersUserIdGet,
    updateUserApiV1UsersUserIdPut,
    deleteUserApiV1UsersUserIdDelete,
    getDiagnosesApiV1DiagnosesGet,
    createDiagnosisApiV1DiagnosesPost,
    getDiagnosisApiV1DiagnosesDiagnosisIdGet,
    updateDiagnosisApiV1DiagnosesDiagnosisIdPut,
    deleteDiagnosisApiV1DiagnosesDiagnosisIdDelete,
    getWardsApiV1WardsGet,
    createWardApiV1WardsPost,
    getAvailableWardsApiV1WardsAvailableGet,
    getWardApiV1WardsWardIdGet,
    updateWardApiV1WardsWardIdPut,
    deleteWardApiV1WardsWardIdDelete,
    getPatientsApiV1PatientsGet,
    createPatientApiV1PatientsPost,
    searchPatientsApiV1PatientsSearchGet,
    getPatientsByDiagnosisApiV1PatientsDiagnosisDiagnosisIdGet,
    getPatientsByWardApiV1PatientsWardWardIdGet,
    getPatientApiV1PatientsPatientIdGet,
    updatePatientApiV1PatientsPatientIdPut,
    deletePatientApiV1PatientsPatientIdDelete,
  };
};
export type RootGetResult = AxiosResponse<unknown>;
export type HealthCheckHealthGetResult = AxiosResponse<unknown>;
export type LoginApiV1AuthLoginPostResult = AxiosResponse<Token>;
export type RegisterApiV1AuthRegisterPostResult = AxiosResponse<unknown>;
export type GetCurrentUserInfoApiV1AuthMeGetResult = AxiosResponse<unknown>;
export type GetUsersApiV1UsersGetResult = AxiosResponse<UserResponse[]>;
export type CreateUserApiV1UsersPostResult = AxiosResponse<UserResponse>;
export type GetUserApiV1UsersUserIdGetResult = AxiosResponse<UserResponse>;
export type UpdateUserApiV1UsersUserIdPutResult = AxiosResponse<UserResponse>;
export type DeleteUserApiV1UsersUserIdDeleteResult = AxiosResponse<void>;
export type GetDiagnosesApiV1DiagnosesGetResult = AxiosResponse<
  DiagnosisResponse[]
>;
export type CreateDiagnosisApiV1DiagnosesPostResult =
  AxiosResponse<DiagnosisResponse>;
export type GetDiagnosisApiV1DiagnosesDiagnosisIdGetResult =
  AxiosResponse<DiagnosisResponse>;
export type UpdateDiagnosisApiV1DiagnosesDiagnosisIdPutResult =
  AxiosResponse<DiagnosisResponse>;
export type DeleteDiagnosisApiV1DiagnosesDiagnosisIdDeleteResult =
  AxiosResponse<void>;
export type GetWardsApiV1WardsGetResult = AxiosResponse<WardResponse[]>;
export type CreateWardApiV1WardsPostResult = AxiosResponse<WardResponse>;
export type GetAvailableWardsApiV1WardsAvailableGetResult = AxiosResponse<
  WardResponse[]
>;
export type GetWardApiV1WardsWardIdGetResult = AxiosResponse<WardResponse>;
export type UpdateWardApiV1WardsWardIdPutResult = AxiosResponse<WardResponse>;
export type DeleteWardApiV1WardsWardIdDeleteResult = AxiosResponse<void>;
export type GetPatientsApiV1PatientsGetResult = AxiosResponse<
  PatientResponse[]
>;
export type CreatePatientApiV1PatientsPostResult =
  AxiosResponse<PatientResponse>;
export type SearchPatientsApiV1PatientsSearchGetResult = AxiosResponse<
  PatientResponse[]
>;
export type GetPatientsByDiagnosisApiV1PatientsDiagnosisDiagnosisIdGetResult =
  AxiosResponse<PatientResponse[]>;
export type GetPatientsByWardApiV1PatientsWardWardIdGetResult = AxiosResponse<
  PatientResponse[]
>;
export type GetPatientApiV1PatientsPatientIdGetResult =
  AxiosResponse<PatientResponse>;
export type UpdatePatientApiV1PatientsPatientIdPutResult =
  AxiosResponse<PatientResponse>;
export type DeletePatientApiV1PatientsPatientIdDeleteResult =
  AxiosResponse<void>;
